server:
  port: 12000

spring:
  application:
    name: viwcy-gateway
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    gateway:
      #网关是否开启服务注册和发现，默认false。重点：一但置为true，单个服务熔断和限流不生效
      discovery:
        locator:
          enabled: false
          #当访问http://127.0.0.1:12000/user-server/**，会被路由到http://127.0.0.1:12001/**
      routes:
        - id: viwcy-user
          #跳转目标，lb://形式配置集群或单节点都行，http://只能配置单节点
          uri: lb://viwcy-user/
          #路由规则
          predicates:
            - Path=/viwcy-user/**
          filters:
            #如果不加该配置，当访问http://127.0.0.1:12000/user-server/**，会被路由到http://127.0.0.1:12001/user-server/**
            - StripPrefix=1
            #单个服务熔断机制
            - name: Hystrix
              args:
                name: viwcy-user
                fallbackUri: 'forward:/fallback/viwcy-user'
        - id: viwcy-goods
          uri: lb://viwcy-goods/
          predicates:
            - Path=/viwcy-goods/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: viwcy-goods
                fallbackUri: 'forward:/fallback/viwcy-goods'
        - id: viwcy-pay
          uri: lb://viwcy-pay/
          predicates:
            - Path=/viwcy-pay/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: viwcy-pay
                fallbackUri: 'forward:/fallback/viwcy-pay'
        - id: viwcy-search
          uri: lb://viwcy-search/
          predicates:
            - Path=/viwcy-search/**
          filters:
            - StripPrefix=1
      # 全局服务熔断，通过网关调用服务A，A宕机或未启动，则会进入服务熔断接口。
      default-filters:
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/fallback/default'

#==================================================================Hystrix服务熔断超时=======================================================================================
hystrix:
  #Hystrix线程池配置
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 2000
      queueSizeRejectionThreshold: 1500
  #Hystrix默认熔断和超时配置，【重点】超时优先级：全局熔断超时>局部熔断超时
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 2000
          thread:
            timeoutInMilliseconds: 5000
    #user-server服务熔断超时配置
    viwcy-user:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    viwcy-goods:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000

jwt:
  passUrls: /viwcy-user/user/register,/viwcy-user/user/login